---

- include_tasks: install_nginx.yml

- include_tasks: configure_nginx.yml

- include_tasks: install_phpmyadmin.yml
  when: (setup_phpmyadmin == "Y" or setup_phpmyadmin == "y")

- include_tasks: install_adminer.yml
  when: (setup_adminer == "Y" or setup_adminer == "y")
