---

- name: Install PHP 8.0
  hosts: webservers
  become: yes
  vars_files:
    - vars/allocation.yml
    - vars/global.yml
    - vars/php.yml
  vars_prompt:
    - name: "php_max_execution_time"
      prompt: "Masukan PHP max_execution_time "
      default: "15"
      private: no
  roles:
    - php
