---

- name: Ensure Anonymous user(s) are not in the database
  mysql_user:
    name: ""
    host: "{{ item }}"
    state: absent
  with_items:
    - "{{ ansible_hostname }}"
    - "{{ inventory_hostname }}"
    - "127.0.0.1"
    - "::1"
    - "localhost"

- name: Remove the test database
  mysql_db:
    name: test
    state: absent

- name: Update MySQL root password for all root accounts
  mysql_user:
    name: root
    host: "{{ item }}"
    password: "{{ mysql_root_password }}"
    login_user: root
    login_password: "{{ mysql_root_password }}"
    check_implicit_admin: yes
    priv: "*.*:ALL,GRANT"
    state: present
  with_items:
    - "127.0.0.1"
    - "localhost"
    # - "%"

