---

- include_tasks: fix_locale.yml

- include_tasks: upgrade_packages.yml

- include_tasks: install_essential_packages.yml

- include_tasks: activate_swap.yml
  when: (activate_swap_file == "Y" or activate_swap_file == "y")
