---

- name: Install Software Properties Common
  apt:
    name:
      - software-properties-common
    state: latest
    autoclean: yes

- name: Add PHP APT Repository
  apt_repository: 
    validate_certs: no
    repo: 'ppa:ondrej/php'
    state: present 
    update_cache: yes

- name: Install PHP 8.0
  apt:
    name:
      - php8.0
      - php8.0-bcmath
      - php8.0-cli
      - php8.0-cgi
      - php8.0-common
      - php8.0-curl
      - php8.0-gd
      - php8.0-mysql
      - php8.0-sqlite3
      - php8.0-fpm
      - php8.0-mbstring
      - php8.0-intl
      - php8.0-xsl
      - php8.0-xml
      - php8.0-zip
      - php8.0-opcache
    state: latest
    autoclean: yes
